Mier03/TeknoSpace

login.php, signup.html, style.css
-in the signup and in css I adjusted the colors 
-and in login.php I updated the new feature of the frontend
=> [Adjustment][MIER]-add-selectusertype-frontend

signup.html
- i moved the container that contains the select feature in signup.html
=> [Mier]-move-select-container

SUNGAHID/homepage-styles.css, SUNGAHID/homepage.html
=> [FEATURE][SUNGAHID] Student_Homepage

SUNGAHID/homepage.html
- Fixed Wrong HTML path
+ Camus -> Camus_Welcome
=> [Adjustment][CAMUS] Fixed Error

Camus_Welcome/welcome.php, SUNGAHID/adminHomepage.php, SUNGAHID/homepage.php
- linked welcome.php
- linked homepage.php
- linked adminHomepage.php
=> [Adjustment][MITCH] Linking pages

SUNGAHID/studentHomepage.php, php/config.php, php/loginPhp.php
- linked log in page for each user type
=> [Adjustment][SANTILLAN] user type log in page

.vscode/settings.json, SUNGAHID/Admin_Homepage.html, SUNGAHID/Admin_Homepage.js, SUNGAHID/Admin_styles.css, SUNGAHID/create_post.php, SUNGAHID/fetch_posts.php
Admin feature with php where they can create and publish post. Not yet finished.
=> [ADJUSTMENT][SUNGAHID]Can create post

SUNGAHID/studentHomepage.php, common-auth.css, login.php, php/config.php, php/loginPhp.php, signup.css, signup.php
- session_start is declared in loginPHP.php which called in both login ang signup page, so I deleted  it to avoid duplication and to remove the issue
=> fix: errors-login&signup

Camus_Welcome/welcome.css, Camus_Welcome/welcome.html, Camus_Welcome/welcome.js
- Fixed page (hopefully)
- NAKAKACRY NA GUYS
=> [Adjustment][CAMUS] welcome page adjustment

Camus_Welcome/welcome.php
- changed my welcome.php to match contents with my welcome.html, also added filepaths to login button and signup button to ".../login.php" and "../signup.php" respectively
=> [Adjustment][CAMUS] PHP adjustment

SUNGAHID/Admin_Homepage.html, SUNGAHID/Admin_Homepage.js, SUNGAHID/Admin_styles.css, SUNGAHID/create_post.php, SUNGAHID/fetch_posts.php
Separated each posts in the timeline and make the like and comments work using js in Faculty side
=> [ADJUSTMENT][SUNGAHID]Separated posts

SUNGAHID/Profile_Page.html, SUNGAHID/Profile_styles
Added Profile Page for Faculty. Still deciding if this would be of use for Profile Page of students.
=> [FEATURE][SUNGAHID]Profile Page

SUNGAHID/ADMIN.php, SUNGAHID/Admin_styles.css, config.php, login.php, loginPhp.php
=> [Feature][MITCH] adminPage

SUNGAHID/Admin_styles.css, SUNGAHID/adminHomepage.php, SUNGAHID/allAccounts.php, SUNGAHID/verify.php
- displayed database -search button not finished yet
=> [Adjustment][MITCH] getDatabase

SUNGAHID/Profile_Page.js
Javascript for Faculty Homepage
=> [ADJUSTMENT][RAIN]Javascript for Faculty Homepage

Camus_Welcome/welcome.html, SUNGAHID/Student_Homepage.html, SUNGAHID/Student_Homepage.js, SUNGAHID/Student_styles.css
Faculty Homepage is updated where every posts posted are separated.
=> Updated Faculty homepage

Profile/Profile_Page.php, Users/fetch_posts.php, config.php
Wrong branch but edited fetch posts php where their profile is seen, also in profile page
=> [Adjustment][Rain]Updated fetch posts

Profile/delete_post.php, Users/ADMIN.php, Users/Admin_styles.css, Users/Student_styles.css, Users/facultyHomepage.php, Users/studentHomepage.php
- also I add bg on the homepage of faculty and admin
=> [BACKEND] Adjustment on deletepost

Users/allAccounts.php, Users/delete_user.php, Users/update_user.php, Users/verify.php, Users/verify_user.php
- added verify database
- verify user
- delete user
- edit/update user check for duplicates first before verifying (id number or email)
=> [Feature][MITCH] verifyUsers

LostAndFound/adminLostFound.php, LostAndFound/facultyLostFound.php, LostAndFound/studentLostFound.php, Users/ADMIN.php
=> [Feature][MITCH] Loat and Found

Users/Admin_styles.css, Users/create_post.php, Users/facultyHomepage.php, Users/post.js
with important toggle but no function
=> [ADJUSTMENT][RAIN]

Login-Signup/loginPhp.php, Login-Signup/signup.php, LostAndFound/adminLostFound.php, LostAndFound/facultyLostFound.php, Maintenance/adminMaintenance.php, Maintenance/facultyMaintenance.php, Users/ADMIN.php, Users/allAccounts.php, Users/facultyHomepage.php, Users/verify.php, Users/verify_user.php
- fixed pop up for all
- fixed verify for the password
=> [FIX][MITCH] pop up post

LostAndFound/adminLostFound.php, LostAndFound/facultyLostFound.php, LostAndFound/post.js, Maintenance/adminMaintenance.php, Maintenance/facultyMaintenance.php, Maintenance/post.js, Users/ADMIN.php, Users/Admin_styles.css, Users/post.js, config.php
- I fixed the create post both admin and faculty .
=> [BACKEND] Fixed create post

Users/ADMIN.php, Users/auth.php, Users/authno.php, Users/facultyHomepage.php, Users/studentHomepage.php
- Added auth.php and authno.php for unauthorized accesses for homepages
+ when users try to input teknospace/USERS/ADMIN.php, it will run through auth.php if theres a log in credential in pc, if not, go to authno.php page to view unauthorized access to user with a hyperlink login to the loginpage
Bugs:
- Does not work on facultyHomepage.php (maybe because naka log in ko)
=> [Feature][CAMUS] Unauthorize Access to Homepages

LostAndFound/adminLostFound.php, LostAndFound/facultyLostFound.php, LostAndFound/post.js, Maintenance/adminMaintenance.php, Maintenance/facultyMaintenance.php, Maintenance/post.js, Users/ADMIN.php, Users/Admin_styles.css, Users/facultyHomepage.php, Users/post.js, config.php
=> [ADJUSTMENT][RAIN]CONTINUATION

Login-Signup/loginPhp.php, Login-Signup/passwordReset.php, Login-Signup/signup.php, Users/allAccounts.php, config.php
- usertype signup
- verify for faculty
- admin can reset password
=> [Adjustment][MITCH] userType

Maintenance/facultyMaintenance.php, Maintenance/maintenance_post.php, Users/Admin_styles.css, Users/Student_styles.css, Users/create_post.php, Users/facultyHomepage.php, Users/fetch_posts.php, Users/post.js, Users/postquery.js, config.php
This is how the important post display
I added column from the posts table
=> [BACKEND[  Integrated post important status

Profile/Profile_Page.php, Users/ADMIN.php, config.php
design toggle for edit, delete and make or remove importance
=> [Adjustment][MITCH] designForToggle

Profile/Profile_Page.php, config.php
- design for profile toggle
- important post for admin
=> [Adjustment][MITCH] admin&profile

Login-Signup/admin_reset_pass.php, Login-Signup/finalForgotPass.php, Login-Signup/loginPhp.php, Login-Signup/mailer.php, mailconfig.php
- admin can reset
- user can forgot password
- token is remove once successfully changed the password
- read-only fields working properly
=> [Fix][MITCH] resetPassword

Login-Signup/login.php, Profile/Profile_Page.js, Profile/Profile_Page.php, Users/ADMIN.php, Users/Admin_styles.css, Users/Student_styles.css, Users/facultyHomepage.php, Users/studentHomepage.php
- Fixed issue where logout modal on Profile Page doesn't work, (Closes Burger Icon when Logout is clicked)
=> [Adjustment][CAMUS] Profile Page Logout Modal

Login-Signup/loginPhp.php, Users/ADMIN.php, Users/auth.php, Users/facultyHomepage.php, Users/logout.php, Users/studentHomepage.php
- Website will now forget the user's credentials after logging out How to test:
Log in with any userType, then copy the url of the homepage ,log out and paste the link on a tab -> should show "unauthorized access" when user is logged in
=> [Feature][CAMUS] Credential forgetting

Users/Admin_styles.css, Users/allAccounts.php, Users/verify.php
=> [Adjustment][MITCH] adminDesign

Login-Signup/loginPhp.php, Users/verify_user.php
- faculty can now insert profile details once verified
- no conflicts with the primary id between verify and users table
-
=> [Fix][MITCH] facultyProfileError

LostAndFound/adminLostFound.php, LostAndFound/facultyLostFound.php, LostAndFound/studentLostFound.php, Maintenance/adminMaintenance.php, Maintenance/facultyMaintenance.php, Maintenance/studentMaintenance.php, Profile/Profile_Page.php, Users/ADMIN.php, Users/Admin_styles.css, Users/Student_styles.css, Users/facultyHomepage.php, Users/studentHomepage.php
Resize adjustments on all pages
=> [ADJUSTMENT][RAIN][RESIZE FEATURE]

LostAndFound/admin.js, LostAndFound/adminLostFound.php, Maintenance/admin.js, Maintenance/adminMaintenance.php, Users/allAccounts.php, Users/verify.php
- all accounts linked to maintenance and lost and found
- verify accounts linked to maintenance and lost and found
=> [Fix][MITCH] linkedManageAccount

LostAndFound/adminLostFound.php, LostAndFound/facultyLostFound.php, LostAndFound/fetch-LF-post.php, LostAndFound/post.js, LostAndFound/studentLostFound.php, Maintenance/adminMaintenance.php, Maintenance/facultyMaintenance.php, Maintenance/maintenance_post.php, Maintenance/post.js, Maintenance/studentMaintenance.php, Users/Student_styles.css, Users/facultyHomepage.php, Users/studentHomepage.php
- Added Image Modals to ff
+ faculty maintenance & l&f
+ admin maintenance & l&f
+ student maintenance & l&f
=> [Adjustment][CAMUS] Added Image Modal

LostAndFound/fetch-LF-post.php, Profile/update_status.php, Users/create_post.php
-  when the lost post change into found, the post will be on the top of the posts.
- when the lost number two post was found, the posts will be on top
- and also i add column in the posts table, which is the updated_status_at, it's type is timestamp and default on current_timestamp
=> [BACKEND] Lost & found posts display

Profile/Profile_Page.php, Profile/delete_comment.php, Profile/update_comment.php
- edit comment for students -delete comment for students
=> [Feature][MITCH] edit&delete-comment

Maintenance/maintenance_post.php, Profile/Profile_styles.css, Profile/update_importance.php
- in this code, i added column in the posts table which is updated_important_at
- when the post change from important to unimportant, the post will become first of the post, and also to the unimportant to important .
=> [BACKEND] Displaying the priority post

Maintenance/facultyMaintenance.php, Users/Admin_styles.css, Users/allAccounts.php, Users/facultyHomepage.php, Users/post.js, Users/verify.php
=> [adjustment][RAIN]CREATE POST

Profile/Profile_Page.js, Profile/Profile_Page.php, Profile/Profile_styles.css, Profile/delete_comment.php, Profile/update_comment.php, Users/verify.php
- and also i added a css for the text area in editing the post and comment
- i adjust the css of the toggle comment
=> [BACKEND] Edit & delete comment proper handling

LostAndFound/adminLostFound.php, LostAndFound/facultyLostFound.php, Maintenance/facultyMaintenance.php, Users/ADMIN.php, Users/facultyHomepage.php
Fix Bugs for burger icon lost and found admin
=> [FIX][SUNGAHID]Fix bugs

Login-Signup/loginPhp.php, Users/verifyFaculty.php, config.php
- student account needs verification from the admin
=> [Adjustment][MITCH] verifyStudAccount

lostandfound/adminLostFound.php, lostandfound/facultyLostFound.php
=> [adjustment][rain]lost and found toggle delete

aboutUs.php, welcome/aboutus.css
edited welcome page for TeknoSpace to maintain branding
=> [ADJUSTMENT][RAIN]edited welcome

users/Admin_styles.css
=> [ADJUSTMENT][RAIN]edited-admin-styles

login-signup/loginPhp.php, login-signup/signup.css, login-signup/signup.php
- Added A signup modal
+ When users register, a signup modal will pop up "Successfully Signed In"
=> [Feature][CAMUS] Sign up modal

profile/Profile_Page.js, profile/Profile_Page.php, profile/Profile_styles.css
- Modals Added to:
+ Deleting Posts
+ Editing Posts
+ Found Item (!)
! = Error
Found Item Error:
Instantly Goes found after clicking (Not waiting for confirmation)
Future Addition:
-  Comments Deleting and Editing has to have A modal as well
=> [Feature][CAMUS] Modals for Deleting/Editing

profile/Profile_Page.js
=> [ADJUSTMENT][RAIN]Profile js

users/facultyHomepage.php
=> [Adjustment][Rain]Updated facultyHomepage.php

users/mainHomepage.php
=> [Fix][MITCH] manageAccount

users/mainHomepage.php
logout function in mainHomaepage
=> [Adjustment][rain]logout

profile/Profile_styles.css
=> [ADJUSTMENT][RAIN]PROFILE
